### ISSUE TITLE
Verify if email is registered?

### ISSUE THREAD

**Issue by saulpalv** [mongodb/docs-realm#1219]
in firebase auth you can know if a specific email has a linked account using `auth.fetchSignInMethodsForEmail` i wonder if this can be achieved in realm, in order to ask first user email, then show the appropriate UI, like the https://account.mongodb.com/account/login login form

not sure if the docs even mentioned this feature, i tried but couldn't find it

**Comment by cbush** [comment]
Hey @saulpalv, thanks for your question. I don't think you can get this information from an email address alone.

If you already have the email user, can see their other linked identities through the identities property. For example, in the Node SDK you can use [User.identities](https://docs.mongodb.com/realm-sdks/js/latest/Realm.User.html#identities); in Swift/Obj-C it's [here](https://docs.mongodb.com/realm-sdks/objc/latest/Classes/RLMUser.html#/c:objc(cs)RLMUser(py)identities).

Unfortunately I don't think there's a good way to look up a user by email first without getting the password as well. I'd encourage you to raise this feature request here: https://feedback.mongodb.com/forums/923521-realm

Hope this helps!

**Comment by cbush** [comment]
Closing as answered.
