### ISSUE TITLE
mistaken reference to Core Data in Kotlin Realm docs

### ISSUE THREAD

**Issue by drmarkpowell** [mongodb/docs-realm#2487]
## Is there something wrong with existing docs content, or is something missing from the docs?

mistake

## If this is related to existing docs content, what page or pages are affected?

https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/overview/

## Which SDK does this issue affect?

Kotlin

## What would you like to see in the docs that isn't already there?

The text refers to "an alternative to Sqlite and Core Data. Core Data is an Apple platform database that has no relevance to Android. Perhaps comparing Realm to Room database and Sqlite would be better for the Android audience.

## If the content is technical, can you link to an example implementation?

N/A

## Where do you feel this content belongs?

no change

**Comment by cbush** [comment]
Thanks for raising! We'll get that fixed up.

By the way, you can also use the Feedback Widget on any page to send us a message. We read everything that comes in!

**Comment by dacharyc** [comment]
Closing this issue now since we've merged a fix that should be live in the docs. Thank you for bringing this to our attention!
