### ISSUE TITLE
Wrong Kotlin data type definition in Realm Query Language documentation

### ISSUE THREAD

**Issue by edualonso** [mongodb/docs-realm#2542]
## Is there something wrong with existing docs content, or is something missing from the docs?

Something is wrong.

## If this is related to existing docs content, what page or pages are affected?

https://www.mongodb.com/docs/realm/realm-query-language/#examples-on-this-page

## Which SDK does this issue affect?

Kotlin SDK code snippet

## What would you like to see in the docs that isn't already there?

The following line is incorrect:
```
lateinit var tasks: Array<Task>
```
`Array`s are not valid data types. The field should be a `RealmList<Task>` instead.

## If the content is technical, can you link to an example implementation?

This error might have flown under the radar because of the following bug in the Kotlin SDK: https://github.com/realm/realm-kotlin/issues/1226

## Where do you feel this content belongs?

N/A.

## Other Comments
None :-)

**Comment by cbullinger** [comment]
Fixed and update deployed.
