### ISSUE TITLE
Replace all instances of KMM word with KMP in Kotlin example

### ISSUE THREAD

**Issue by Kaaveh** [mongodb/docs-realm#3080]
If allowed, I would like to refactor the Kotlin example and replace all instances of the KMM word with KMP in package names due to Jetbrain's deprecation of KMM.

https://github.com/mongodb/docs-realm/tree/master/examples/kotlin

**Comment by dacharyc** [comment]
Hey, @Kaaveh , thanks for the suggestion and the offer. The Kotlin app in this repository is a test harness for our code examples that we do not expose directly in our documentation. The app itself isn't an example - the code we generate from it constitutes our examples. We do not expose the KMM naming in any of the public-facing documentation examples. With that in mind, this work does not seem needed at this time.

We appreciate the suggestion!
