### ISSUE TITLE
Allowing only login, not creating account

### ISSUE THREAD

**Issue by step135** [mongodb/docs-realm#3128]
I don't see in documentation how to disable creating accounts in MongoDB Atlas through Realm and using it only for login to existing accounts. 

It is important for security reasons that developers can restrict creation of accounts only to server side, not enable it in Realm JavaScript.

**Comment by dacharyc** [comment]
Hi @step135 - which authentication method are you trying to use to login from the SDKs? The only authentication method where you can control whether the SDK creates new accounts is email/password authentication. For more information, see: [Create and Delete Users](https://www.mongodb.com/docs/realm/sdk/node/users/create-delete-users/) in our SDK documentation, or [Create an App User](https://www.mongodb.com/docs/atlas/app-services/users/create/) in our Atlas App Services documentation.

For other authentication methods, we rely on the authentication provider to validate whether or not a user should be able to login. You can see more details about the authentication providers on the [Authentication Providers page](https://www.mongodb.com/docs/atlas/app-services/authentication/#std-label-authentication-providers) in the App Services documentation.

**Comment by dacharyc** [comment]
So with Email/Password users, there are actually two different methods involved:

- [`emailPasswordAuth.registerUser()`](https://www.mongodb.com/docs/realm/sdk/node/users/manage-email-password-users/#register-a-new-user-account) creates the user account.
- [App.login()](https://www.mongodb.com/docs/realm/sdk/node/users/authenticate-users/#email-password-user) with an `emailPassword` credential actually logs the user in.

You could potentially implement a client that just doesn't contain the `registerUser()` method so the client is incapable of creating new user accounts. You or a trusted member of your team could manually create the user accounts, so there is no automatic creation - the [Create an App User page](https://www.mongodb.com/docs/atlas/app-services/users/create/#manually-create-an-email-password-user) in the App Services documentation has details about how to manually create email/password users.

Does this solve your use case?

**Comment by step135** [comment]
You are completely not answering. How to disable 'registerUser' in Realm?

**Comment by dacharyc** [comment]
If you don't use the `registerUser()` method in your client application, then users can't register new accounts. You can omit the method call entirely from your client code. If that doesn't solve your use case, can you share a little more about what you're trying to do?

**Comment by step135** [comment]
@dacharyc It is completely irrelevant comment and totally unhelpful to read it. Your recommendation will not disable `registerUser` in any way. It is again completely not tackling the issue I reported.

**Comment by dacharyc** [comment]
Is your use case that other developers will be writing code using the SDK and you want to prevent other developers from implementing `registerUser()` in app code?
